import { BrowserSession } from "../dist/browser/session.js";
import { ToolExecutor } from "../dist/browser/tools.js";
import fs from "node:fs"; import os from "node:os"; import path from "node:path";
const runDir = fs.mkdtempSync(path.join(os.tmpdir(),"sn-vid-"));
const s = new BrowserSession({ headed:false, actionTimeoutMs:6000, artifactsDir: runDir, video:true });
await s.start();
await s.page.setContent("<h1>Recording test</h1><input placeholder='x'><button>Go</button>");
const snap = await s.snapshot();
const inp = snap.elements.find(e=>e.tag==="input");
const ex = new ToolExecutor(s);
await ex.execute("type", { index: inp.index, text: "hello world" });
await s.page.waitForTimeout(400);
await ex.execute("scroll", { direction: "down" });
await s.close();
console.log("videoFile:", s.videoFile);
const files = fs.readdirSync(runDir);
const webm = files.filter(f=>f.endsWith(".webm"));
const size = webm.length ? fs.statSync(path.join(runDir, webm[0])).size : 0;
console.log("run dir files:", files.join(", "));
console.log("webm size:", size, "bytes");
const ok = s.videoFile && s.videoFile.endsWith(".webm") && webm.length===1 && size>1000;
console.log(ok ? "\nOK — run recorded to a playable .webm." : "\nFAIL");
process.exit(ok?0:1);
