import type { PageProfile } from "./browser/profile.js";

export interface ScaffoldedSpec {
  /** The structured spec object (a valid TestSpec once task/intent are filled). */
  spec: Record<string, unknown>;
  /** A commented YAML rendering that guides the user to complete it. */
  yaml: string;
}

function hostName(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

/**
 * Turn a captured page profile into a starter spec. The task/intent are
 * grounded in what is actually on the page (login form, primary actions,
 * headings) but left as clearly-marked TODOs for the author to refine.
 */
export function scaffoldSpec(profile: PageProfile, opts: { name?: string } = {}): ScaffoldedSpec {
  const host = hostName(profile.url);
  const appName = opts.name ?? profile.title?.split(/[|\-–—·]/)[0].trim() ?? host;
  const tags = ["smoke", ...(profile.hasLogin ? ["auth"] : [])];

  let title: string;
  let task: string;
  let intent: string;

  if (profile.hasLogin) {
    const loginForm = profile.forms.find((f) => f.hasPassword);
    const fields = loginForm?.fields.join(", ") || "email, password";
    title = `${appName}: log in`;
    task = `Log in using the provided credentials (form fields: ${fields})${
      loginForm?.submitLabel ? `, then submit via "${loginForm.submitLabel}"` : ""
    }.`;
    intent = `After logging in, the app shows an authenticated view (account menu, dashboard, or the user's name) — not the login form or an error.`;
  } else {
    const action = profile.primaryActions[0];
    const heading = profile.headings[0];
    title = `${appName}: ${action ? `use "${action}"` : "primary flow"}`;
    task = `TODO: describe the user action to test${
      action ? ` (e.g. click "${action}")` : ""
    }${heading ? ` on the "${heading}" page` : ""}.`;
    intent = `TODO: describe what success looks like — the observable end state that proves the task worked.`;
  }

  const spec: Record<string, unknown> = {
    title,
    tags,
    task,
    intent,
    app: profile.hasLogin
      ? { name: appName, url: profile.url, auth: { username: "TODO@example.com", password: "TODO" } }
      : { name: appName, url: profile.url },
  };

  return { spec, yaml: renderYaml(spec, profile) };
}

function q(s: string): string {
  // Quote and escape for a YAML double-quoted scalar.
  return `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function renderYaml(spec: Record<string, unknown>, profile: PageProfile): string {
  const app = spec.app as Record<string, unknown>;
  const auth = app.auth as Record<string, unknown> | undefined;
  const lines: string[] = [
    `# Generated by 'sentinel init' from ${profile.url}`,
    `# Fill in the TODOs, then run:  sentinel run this-file.yaml`,
    ``,
    `title: ${q(String(spec.title))}`,
    `tags: [${(spec.tags as string[]).join(", ")}]`,
    `task: ${q(String(spec.task))}`,
    `intent: ${q(String(spec.intent))}`,
    `app:`,
    `  name: ${q(String(app.name))}`,
    `  url: ${q(String(app.url))}`,
  ];
  if (auth) {
    lines.push(`  auth:`);
    lines.push(`    username: ${q(String(auth.username))}   # TODO: real credentials (redacted in reports)`);
    lines.push(`    password: ${q(String(auth.password))}`);
  }
  // Surface what was detected as guidance, commented out.
  lines.push(``, `# --- detected on the page (for reference) ---`);
  if (profile.headings.length) lines.push(`# headings: ${profile.headings.slice(0, 5).join(" | ")}`);
  if (profile.primaryActions.length)
    lines.push(`# actions: ${profile.primaryActions.slice(0, 8).join(" | ")}`);
  for (const f of profile.forms.slice(0, 3)) {
    lines.push(`# form: [${f.fields.join(", ")}]${f.hasPassword ? " (has password)" : ""}`);
  }
  return lines.join("\n") + "\n";
}
